[package]
name = "sharecore"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-schema = { workspace = true }
serde = { workspace = true }
cosmwasm-std = { workspace = true }
thiserror = { workspace = true }
cw-storage-plus = { workspace = true }
universal-token = { workspace = true }
access-control = { workspace = true }
stakecore = { workspace = true, features = ["library"] }

[features]
default = []
library = []
cosmwasm_1_1 = ["stakecore/cosmwasm_1_1"]
cosmwasm_1_2 = ["cosmwasm-std/cosmwasm_1_1", "stakecore/cosmwasm_1_2"]
cosmwasm_1_3 = ["cosmwasm-std/cosmwasm_1_2", "stakecore/cosmwasm_1_3"]
cosmwasm_1_4 = ["cosmwasm-std/cosmwasm_1_3", "stakecore/cosmwasm_1_4"]
cosmwasm_2_0 = ["cosmwasm-std/cosmwasm_1_4", "stakecore/cosmwasm_2_0"]
cosmwasm_2_1 = ["cosmwasm-std/cosmwasm_2_0", "stakecore/cosmwasm_2_1"]
cosmwasm_2_2 = ["cosmwasm-std/cosmwasm_2_1", "stakecore/cosmwasm_2_2"]

#[profile.release]
#opt-level = 3
#debug = false
#rpath = false
#lto = true
#debug-assertions = false
#codegen-units = 1
#panic = 'abort'
#incremental = false
#overflow-checks = true
